### ISSUE TITLE
DUDAS

### ISSUE THREAD

**Issue by lorenaagm** [albamiguel/Inaccesibilidad-sanitaria-y-efectos-en-salud#49]
Queremos mejorar la estética de gráfico, pero no conseguimos que nos salga de otro color (nuestra idea es que cada barra sea de un color).

**Comment by lorenaagm** [comment]
@ajcanepa

**Comment by albamiguel** [comment]
He conseguido cambiar que cada barra sea de un color distinto, usando el comando fill =rainbow(19), pero no se si es la mejor manera de hacerlo. El código está en el commit (Cambio colores -barra).

@ajcanepa

**Comment by ajcanepa** [comment]
> He conseguido cambiar que cada barra sea de un color distinto, usando el comando fill =rainbow(19), pero no se si es la mejor manera de hacerlo. El código está en el commit (Cambio colores -barra).
> 
> @ajcanepa

Perdón por llegar tarde.
El código es correcto y como lo hablamos en clases, a nivel de código está bien manipular un color (si el resto está OK, os sumará puntos). Ahora que rainbow(19) sea la mejor elección, de eso no me preocuparía tanto auqnue siempre lo estético hay que cuidarlo.
