### ISSUE TITLE
Duda 2

### ISSUE THREAD

**Issue by albamiguel** [albamiguel/Inaccesibilidad-sanitaria-y-efectos-en-salud#50]
Como te comente por correo en el primer gráfico el que intentamos relacionar la inaccesibilidad sanitaria con los motivos económicos, elimine finalmente medicamento recetado ya que no te indica los tipos de medicamentos y no entiendo muy bien la relacion que puede llegar a tener con el tema. Además no consigo ordenar el eje y para que siga una escala lógica, por lo que el resultado que  nos da el grafico no es correcto.
![image](https://user-images.githubusercontent.com/80346538/143486668-5fda9504-0e66-4fd2-b677-cc5d35da6d60.png)

**Comment by albamiguel** [comment]
@ajcanepa

**Comment by ajcanepa** [comment]
> @ajcanepa

Era el tema de la clase de la variable `y`. Si es factor (ó cáracter) o cualquier cosa que no sea numérica no lo graficará bien.
